### ISSUE TITLE
Stream is not rendered pixel-perfect

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#1416]
There is a bug in the NDK decoder logic, the returned AHardwareBuffers contain a small amount of padding that when interpolated linearly in OpenGL it causes the image to lose sharpness. Thanks to @deiteris for the discovery.

**Comment by deiteris** [comment]
Just to clarify a bit:
1. The current logic always aligns the resolution by 32px, which is not ideal and sometimes produces wrong resolution (i.e., 3664x1920 becomes 3648x1920).
2. If we remove the alignment and perform video encoding on resolutions that are not aligned by 16px (h264) or 32px (h265), encoder automatically adds some amount of padding to maintain the correct picture size (3664x1920 becomes 3680x1920 + information about right padding). 
3. When decoded by NDK, the decoder produces `Image`, that specifies correct dimensions after cropping, but its underlying `AHardwareBuffer` still has the original size. I wouldn't consider this an NDK bug, because the Image is produced from the underlying buffer.

The problem is here: https://github.com/alvr-org/ALVR/blob/master/alvr/client_core/src/platform/android.rs#L314
```
queued_image
    .image <-- get_width() and get_hight() is 3664x1920
    .get_hardware_buffer() <-- width and height is 3680x1920
    .unwrap()
    .as_ptr()
    .cast(),
```

**Comment by zarik5** [comment]
Fixed by #1434

**Comment by zarik5** [comment]
Ops, nevermind.

**Comment by haukepribnow** [comment]
While investigating #2579, I came across this older bug report. Some strange scaling/interpolation because of an incorrect resolution (as reported in this issue) **might** explain #2579.

Even though I'm not full convinced myself, I still started working on cropping the hardware buffer when rendering it onto the staging texture. Some very early progress can be found here: https://github.com/alvr-org/ALVR/compare/7ece87b1cf56c9a5dd3dbd5ed913a80b1766e508...haukepribnow:ALVR:64e6b22c83c109afdbf039fc129189996c6db52f

@zmerp - As you self-assigned this issue, I was wondering if you could take a first look at how I approached this topic. Am I on the right track here? Or did you have a different idea how to address this?

I know there is quite some work yet to be done... FFE is completely disregarded yet and one of the C API function completely breaks. But I wanted to get some first feedback before I invest too much more time.

**Comment by zmerp** [comment]
Sorry for taking so long on this. Sjnce this issue was opened, the have been multiple rewrites of the graphics code and yet this is not fixed. I should do this soon.

**Comment by zmerp** [comment]
@haukepribnow it seems your implementation is a little more complicated than it needs to be, but i'll review thoroughly another time, tomorrow maybe

**Comment by haukepribnow** [comment]
During a cleanup of my email inbox I came across this thread again. Any update? :-)
