### ISSUE TITLE
OS Error 11, have to restart alot of times to connect properly

### ISSUE THREAD

**Issue by dualposition** [alvr-org/ALVR#2296]
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware windows 11 home ver 23H2 asus tuf gaming f15 fx506lh_fx506lh
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz

**GPU**: I cant find it anywhere but I'm sure its some nvidia GeForce gtx shit

**GPU Driver Version**: where do I find tha

**Audio**: what

### Installation
**ALVR Version**: the newest

**ALVR Settings File**: ???

**SteamVR Version**: also the newest

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x]  Portable (`zip`) yes
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): winver????

**Comment by cheezygt** [comment]
also gestures no work

**Comment by danielkariv** [comment]
Can confirm this issue too. My system is I7 4770, RTX 3060Ti, 32gb ram, running Windows 10. The headset is Quets 3.
ALVR is usually running together with ADBforward for usb connection but I also saw the problem when running wirelessly too. 
I notice this issue since v20.7, till recent v20.9.1 version and also in developer builds over the last few months.

I don't know what makes this issue pop up. Most of the times, I have basically open ALVR-SteamVR, open ALVR client app, get the error 11 (handshake failed), and then I am closing SteamVR and open it again, and then it should works. But it isn't 100% of the times, I have found myself having to spend like 30 mins of closing and openning, or even playing with settings just to make it finally connect. 
The biggest issue with it that even if you pass all of it, the moment the headset disconnect (like, if I take it off for a few minutes and come back), it usually just fails to reconnect, it shows this error again, and I could restart SteamVR to 'fix it' but it also means that whatever I run before need to reopen too, making it a long process to come back to where I was each time (which, does limits how and how much I use VR right now..).

**Comment by zarik5** [comment]
I'm having the same issue, on and off. It's too random for me to even begin to debug. @danielkariv so you say this started happening in 20.7? is this accurate?

**Comment by danielkariv** [comment]
> I'm having the same issue, on and off. It's too random for me to even begin to debug. @danielkariv so you say this started happening in 20.7? is this accurate? have you tried installing v20.6 now and test?

Sorry, I wasn't clear about it, no, I didn't test it on older versions than v20.7. I more of wanted to say that I notice it for long period of time, over multiple versions, but not that it necessarily started with v20.7.

**Comment by zarik5** [comment]
@danielkariv could you give a try to older versions? Using the launcher is rather easy

**Comment by The-personified-devil** [comment]
> @danielkariv could you give a try to older versions? Using the launcher is rather easy

tbh maybe the opposite would help, namely trying mdns in nightly

**Comment by zarik5** [comment]
@danielkariv from experience, I also don't seem to reproduce the bug anymore recently. not sure what caused it. But I'm pretty sure the I had error 11 also on the steamvr home

**Comment by cheezygt** [comment]
> @danielkariv from experience, I also don't seem to reproduce the bug anymore recently. Not sure what caused it. But I'm pretty sure I had error 11 also on the SteamVR home.

for me the bug still happens

**Comment by zarik5** [comment]
@cheezygt have you tried any prior version? can you find a version not affected by this error?

**Comment by cheezygt** [comment]
> @cheezygt have you tried any prior version? can you find a version not affected by this error?

i don't use prior versions, I started using alvr recently cuz steam link and quest link for some reason don't work, steam link says that I have to use a local network even if I'm on a local network. i feel like the issue is kinda luck based, if you're lucky it will connect first try, if you're not you have to restart steamvr for it to connect, if you're extremely unlucky it will never connect

**Comment by cheezygt** [comment]
also the bug happens on phonevr too

**Comment by zarik5** [comment]
Hm. Try older versions as i told you

**Comment by unluckycord** [comment]
I tried older versions and nothing fixed this. The install APK option does absolutely nothing other than fail, regardless of what version I use, so there is no way to GET an older version on the quest. why does this app do this? The only time this app worked was before I rebooted my computer to get the VB app driver to load. could it be related to VB?

**Comment by Vixea** [comment]
Did you run vb's installer as admin?

**Comment by unluckycord** [comment]
yes, I tried deleting the driver and it made no difference lol, it seems this app has never really worked properly for a lot of users, as there are **countless** examples of people having the same issue, with no way to fix it, then they give up and the thread gets closed before a solution is actually found.

**Comment by zarik5** [comment]
@unluckycord do downgrade an app using adb you first need to uninstall the app manually.

Maybe we could add a uninstall command in the launcher.

**Comment by unluckycord** [comment]
> @unluckycord do downgrade an app using adb you first need to uninstall the app manually.
> 
> Maybe we could add a uninstall command in the launcher.

Ah, thank you so much! When you say uninstall it first, do you mean uninstall the quest app or the desktop app? The app I have on my quest is the official ALVR app on the meta store, as side quest will only point me there anyway.

**Comment by zarik5** [comment]
@unluckycord I meant the Quest app. This is an Android/ADB limitation. they have a check that make succeed installation only if the version is greater than the current installed one.

**Comment by Timocop** [comment]
Is anyone here using VoiceMeeter by any chance? I had this issue too and i figured out that the VoiceMeeter preset is causing it. Using "Custom" and entering "VoiceMeeter Input" in sink and "VoiceMeeter Output" in source fixed the problem. I can reproduce this issue 100%

**Comment by ANBAL534** [comment]
I don't think is related to Voicemeeter, for me its happening in Windows 10 and also in Linux with Alsa/Pipewire . Same behaviour, having to restart SteamVR multiple times for the handshake error to dissapear, and if the headset goes to sleep, when reactivated, the error sometimes appear again.

**Comment by Krutonium** [comment]
Continues happening to me.

**Comment by Krutonium** [comment]
@The-personified-devil Thank you!

**Comment by Eldritch6847** [comment]
Same issue here, trying to play blade and sorcery and even after a hard restart for both my quest 2 and my pc, I still get error 11 over and over. Interesting note is I only started getting this error after updating my windows to version 23H2.

Specs are as listed:
GPU: Radeon rx 7800 XT 
CPU: Ryzen 7 3700x
RAM: 32gb 3200mHz
OS: Windows 11 23H2

**Comment by cheezygt** [comment]
doesnt happen for me anymore but other people have this issue still so idk ill leave this open

**Comment by cheezygt** [comment]
uh devs i think you did something in 20.12.0, it started happening again, it didnt happen in 20.11.0

**Comment by zmerp** [comment]
On Windows 23H2 and enabling microphone streaming I can reproduce the same error. Im not sure the will land in v20.12.1 but it will be fixed soon

**Comment by gongfuture** [comment]
I probably found a way to solve this problem, if someone have same environment with me.
I use Voicemeeter Patato, and use `Automatic` or `Voicemeeter Aux` as headset microphone in ALVR will cause this problem.
I tried set them custom and it works.
Set like this ↓

![Image](https://github.com/user-attachments/assets/2104ab39-406e-4951-a87c-6ccbcfc914f8)

It may can set any devices, names can be found at ...... sorry I'm using Windows in Chinese so I don't know what are they called exactly in English, I can show where you can find it ↓ (read from right to left)

![Image](https://github.com/user-attachments/assets/cab72f47-71c9-48a5-9844-1c32e337fdc1)

NOVICE! If you just copy and paste it, it may not work! Just like the device shows above, it will copy the name as "VB-Audio VoiceMeeter AUX VAIO
"
Yes, It has a newline at end, so remember delete it.

That's all. I can use headset microphone after I did these.

**Comment by InfiniteTerrarian** [comment]
i can confirm this is still an issue today has happened multiple times, unsure how to fix

**Comment by PatentOwl** [comment]
(Similar issue) Okay I was able to boil it down to this issue, [ALVR OS Error 10554 and 10553 when connecting to ALVR #2490](https://github.com/alvr-org/ALVR/issues/2490). Some said its the firewall but that did not make any difference. Here the latest "crashlog" (Sry its german. [...] is just in parts where the same message was repeated often): `16:28:41.927 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
16:32:31.167 [ERROR] Unhandled exception: E06D7363
Stack trace (most recent call last):
#7    Object "", at 00007FFF128E1BB2, in  ?? 
#6    Object "", at 00007FFEB38307BF, in bz_internal_error
#5    Object "", at 00007FFEB3822654, in bz_internal_error
#4    Object "", at 00007FFEB383D1F8, in bz_internal_error
#3    Object "", at 00007FFEB3846BCE, in bz_internal_error
#2    Object "", at 00007FFEB3847B43, in bz_internal_error
#1    Object "", at 00007FFEDCE65267, in CxxThrowException
#0    Object "", at 00007FFF12CDB699, in RaiseException
20:11:42.272 [ERROR] Could not initiate connection for 9717.client: connection timed out
00:53:35.778 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
01:03:12.376 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
05:19:29.471 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
21:47:45.412 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
22:04:54.215 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
11:21:22.500 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
12:41:42.889 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
14:51:41.669 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
14:00:09.278 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
20:40:21.821 [ERROR] Could not initiate connection for 9717.client: connection timed out
20:43:21.728 [ERROR] Could not initiate connection for 9717.client: connection timed out
21:05:16.145 [ERROR] Could not initiate connection for 9717.client: connection timed out
04:21:15.898 [ERROR] Could not initiate connection for 9717.client: connection timed out
04:22:54.214 [ERROR] Error on parsing session config (D:\Custom\Downloads\alvr_streamer_windows\session.json): syntax error at line 1 near: 
04:23:26.202 [ERROR] Could not initiate connection for 9717.client: connection timed out
[...]
16:54:54.553 [ERROR] Could not initiate connection for 9717.client: connection timed out
16:55:13.440 [ERROR] Failed to find resumed state line
21:55:05.636 [ERROR] Failed to find resumed state line
21:55:21.719 [ERROR] Could not initiate connection for 9717.client: connection timed out
21:58:51.833 [ERROR] Could not initiate connection for 9717.client: connection timed out
21:59:49.207 [ERROR] Could not initiate connection for 9717.client: connection timed out
22:36:04.896 [ERROR] Could not initiate connection for 9717.client: connection timed out
16:54:37.172 [ERROR] Handshake error for client.wired: Try again
[...]
16:58:17.205 [ERROR] Handshake error for client.wired: Try again
17:06:39.099 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:41.067 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:44.441 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:46.914 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:48.797 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:50.429 [ERROR] Handshake error for client.wired: Game audio and microphone cannot point to the same device!
17:06:54.131 [ERROR] Handshake error for client.wired: Try again
[...]
22:25:15.569 [ERROR] Handshake error for client.wired: Try again
22:25:32.041 [ERROR] Failed to find resumed state line
22:25:36.386 [ERROR] Handshake error for client.wired: Try again
22:25:57.026 [ERROR] Handshake error for client.wired: Try again
22:26:08.641 [ERROR] Handshake error for client.wired: Try again
22:26:17.844 [ERROR] Failed to find resumed state line
22:26:51.458 [ERROR] Handshake error for client.wired: Try again
[...]
23:53:48.686 [ERROR] Handshake error for client.wired: Try again
23:54:03.709 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:05.670 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:07.695 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:11.701 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
23:54:13.809 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:15.762 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
23:54:17.764 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:19.807 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:22.093 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
23:54:23.991 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
23:54:26.209 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:28.745 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:30.460 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:32.715 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
23:54:34.565 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
23:54:35.839 [ERROR] Could not initiate connection for 9717.client: Eine Anforderung zum Senden oder Empfangen von Daten wurde verhindert, da der Socket nicht verbunden ist und (beim Senden über einen Datagrammsocket mit einem sendto-Aufruf) keine Adresse angegeben wurde. (os error 10057)
02:35:34.898 [ERROR] Failed to find resumed state line
02:35:38.900 [ERROR] Handshake error for client.wired: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:35:41.067 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:35:44.963 [ERROR] Handshake error for client.wired: Try again
02:35:46.087 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
02:35:51.064 [ERROR] Handshake error for client.wired: Try again
02:35:52.074 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:35:56.126 [ERROR] Handshake error for client.wired: Try again
02:35:57.112 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:01.021 [ERROR] Handshake error for client.wired: Try again
02:36:02.008 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:06.950 [ERROR] Handshake error for client.wired: Try again
02:36:07.930 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:11.855 [ERROR] Handshake error for client.wired: Try again
02:36:12.853 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:16.807 [ERROR] Handshake error for client.wired: Try again
02:36:17.875 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:22.078 [ERROR] Handshake error for client.wired: Try again
02:36:23.250 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:27.354 [ERROR] Handshake error for client.wired: Try again
02:36:28.403 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:32.228 [ERROR] Handshake error for client.wired: Try again
02:36:33.212 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:37.027 [ERROR] Handshake error for client.wired: Try again
02:36:37.996 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:41.858 [ERROR] Handshake error for client.wired: Try again
02:36:42.835 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:36:46.829 [ERROR] Handshake error for client.wired: Try again
02:36:47.781 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:32.001 [ERROR] Handshake error for client.wired: Try again
02:41:35.505 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
02:41:40.107 [ERROR] Handshake error for client.wired: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:41.676 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:46.360 [ERROR] Handshake error for client.wired: Try again
02:41:47.851 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:51.372 [ERROR] Handshake error for client.wired: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:52.796 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:41:57.582 [ERROR] Handshake error for client.wired: Try again
02:41:58.798 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:03.589 [ERROR] Handshake error for client.wired: Try again
02:42:05.414 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:09.385 [ERROR] Handshake error for client.wired: Try again
02:42:10.401 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:14.599 [ERROR] Handshake error for client.wired: Try again
02:42:15.622 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:19.615 [ERROR] Handshake error for client.wired: Try again
02:42:20.720 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:24.684 [ERROR] Handshake error for client.wired: Try again
02:42:25.700 [ERROR] Handshake error for 9717.client: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. (os error 10054)
02:42:29.556 [ERROR] Handshake error for client.wired: Try again
02:42:30.771 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:34.678 [ERROR] Handshake error for client.wired: Try again
02:42:35.927 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:40.227 [ERROR] Handshake error for client.wired: Try again
02:42:41.296 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
02:42:45.374 [ERROR] Handshake error for client.wired: Try again
02:42:46.353 [ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)` Notable are errors `[ERROR] Could not initiate connection for 9717.client: Eine Anforderung zum Senden oder Empfangen von Daten wurde verhindert, da der Socket nicht verbunden ist und (beim Senden über einen Datagrammsocket mit einem sendto-Aufruf) keine Adresse angegeben wurde. (os error 10057)` and `[ERROR] Handshake error for 9717.client: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)` as well as this stacktrace `[ERROR] Unhandled exception: E06D7363
Stack trace (most recent call last):
#7    Object "", at 00007FFF128E1BB2, in  ?? 
#6    Object "", at 00007FFEB38307BF, in bz_internal_error
#5    Object "", at 00007FFEB3822654, in bz_internal_error
#4    Object "", at 00007FFEB383D1F8, in bz_internal_error
#3    Object "", at 00007FFEB3846BCE, in bz_internal_error
#2    Object "", at 00007FFEB3847B43, in bz_internal_error
#1    Object "", at 00007FFEDCE65267, in CxxThrowException
#0    Object "", at 00007FFF12CDB699, in RaiseException`

Os error 10057 could only be found in [stackoverflow](https://stackoverflow.com/questions/68694569/python-socket-ssl-oserror-winerror-10057-a-request-to-send-or-receive-data-wa) and [citrix.](https://community.citrix.com/topic/243911-socked-error-10057-on-client-while-accessing-vci-from-remote-network/) one commenter said ` Socket error 10057 means according to Microsoft Error Codes

 

https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2

 

WSAENOTCONN 10057

Socket is not connected.

A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using sendto) no address was supplied. Any other type of operation might also return this error—for example, setsockopt setting SO_KEEPALIVE if the connection has been reset.

 

Check your STA listed in the SF Server from using FQDN to IP Adress of the XenApp Server - If you always use FQDN: verify that your FQDN can be resolved to the correct IP of the STA Server. ` maybe this helps.

Os error 10053 is also on [stackoverflow](https://stackoverflow.com/questions/52955348/what-can-i-do-with-the-socket-error-number-10053) and saying that the firewall is an issue `TLDR; Error 10053 is a WSA Error ([learn.microsoft.com/en-us/windows/desktop/WinSock/…](https://learn.microsoft.com/en-us/windows/desktop/WinSock/windows-sockets-error-codes-2)). It likely means either you have a virus scanner or firewall that is refusing to allow your session.`. The nightly builds of ALVR say A key component of SteamVR isn't working properly. Please restart SteamVR. Thats Steamvr error [309](https://steamcommunity.com/app/250820/discussions/0/4200238856307319447/?ctp=1)wich I cant seem to find a solution on, as its not a driver issue for me.

All this are Issues I have found NO fix for, but maybe this helps in any way.

**Comment by PatentOwl** [comment]
Okay try deleting the session.json in the alvr directory, this at least for me made it possible to connect again. Settings will be reset but can be changed (I dont know to what extend). Please dont mark this as fixed until others tested this and agree upon it being a viable solution. For me the path on the portable instalation was `D:\Custom\Downloads\alvr_streamer_windows\session.json  
`

**Comment by dualposition** [comment]
changed title so it doesnt look like im a 12 year old sniffing glue

**Comment by doublej** [comment]
Same issue. Logs are verbose but not very diagnostic. I feel like when the situation is as such that this bug will arise, it typically happens like 5 - 10 minutes into my game. Have thoroughly pulled all logs leading up to the crash/disconnect but thus far not able to find anything meaningful.

**Comment by gongfuture** [comment]
@StormyNotFound Thanks for getting the first feedback on this solution. But I don't think this method completely solves this problem, because I still have timeout issues from time to time when I use it. This should only be used as a temporary solution as the bug is not fixed.

**Comment by nazarobika** [comment]
ok bot

**Comment by neomoth** [comment]
also encountering this issue, i was able to connect earlier today but installed nightly in order to fix the cuda error since thats what it said to do on the troubleshooting page, and now i get this error.

**Comment by MochyPei** [comment]
The problem appears even on Win 10, frequently with virtual mic but right now i just can't play pcvr through cable even without any mic cause 10053 and 10054 errors, on v20.14.1. When it will be fixed?

**Comment by PatentOwl** [comment]
> The problem appears even on Win 10, frequently with virtual mic but right now i just can't play pcvr through cable even without any mic cause 10053 and 10054 errors, on v20.14.1. When it will be fixed?

The issue is that the exact cause seems unknown. For all I know, it seems to be a connection issue. Whether with incorrectly configured audio devices or like in my case (I assume) instable connections to steamvr and my headset. So disabling microphone or resetting the settings is the first thing Id do. If it doesnt work, reinstall Steamvr, that often works. If it still doesnt work, you have a bigger issue at hand. If some still have this issue after these few and simple steps, please feel free to share your log files.

**Comment by MochyPei** [comment]
> The issue is that the exact cause seems unknown. For all I know, it seems to be a connection issue. Whether with incorrectly configured audio devices or like in my case (I assume) instable connections to steamvr and my headset. So disabling microphone or resetting the settings is the first thing Id do. If it doesnt work, reinstall Steamvr, that often works.

Tried a couple of times, it helps but for a couple of days, maybe weeks, and in one day for no reason, it appears again, lower versions, reinstalling, nothing helps. And seems that is not only problem with windows 10 and virtual audio channels, it appears on windows 11 even without virtual audio channels (my friend tested it with pico 4, i tried it a year ago).
I don't really understand why it happens, but i found same errors when experimented with video streaming from obs in local network, same errors appeared (connection closed by the software and etc.), even code 10053 same, i think it's somehow related with ffmpeg or rtmp.

**Comment by buildbro** [comment]
I fixed this issue for my PhoneVR x ALVR setup by turning off Client Discovery under **Settings** > **Connection** in ALVR Dashboard on my PC.

**Comment by MochyPei** [comment]
> This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Bump, still there

**Comment by brendoncatgaming** [comment]
how soon will this get fixed so i can use the headset mic without having to restart a billion times

**Comment by brendoncatgaming** [comment]
so for me i got it working by disabling all "VB-Audio Voicemeeter VAIO options and and all but "CABLE Output" under "VB-Audio Virtual Cable" in the input section and all but "CABLE" Input in the output section, in the manage sound devices section, windows 10 settings, and setting devices to the "VB Cable" option under the "Headset microphone" option in the audio settings of ALVR

**Comment by Hydroleo50** [comment]
> This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

Bump, still there (pls help i still have this issue) (no pressure tho)

**Comment by ogbaba** [comment]
having this issue as well, disabling "headset microphone" in ALVR settings did the trick

**Comment by Jurangren** [comment]
Try my fixed fork: [https://github.com/Jurangren/ALVR](https://github.com/Jurangren/ALVR)

There is a Windows release available in the fork.

Please let me know if it works properly for you.
