### ISSUE TITLE
Unable to build ALVR on Manjaro/Arch

### ISSUE THREAD

**Issue by Killrmemz** [alvr-org/ALVR#726]
I am unable to build ALVR on my Manjaro KDE install, after lots of trial and error.
I have tried my best to connect the dots regarding what dependencies I need by referencing the dependencies that Gentoo and Ubuntu require for building, as listed in [the build guide](https://github.com/alvr-org/ALVR/wiki/Build-from-source#linux-experimental-build), but in spite of my efforts it fails.
Here's the output:
[Output-buildfail.txt](https://github.com/alvr-org/ALVR/files/6756397/Output-buildfail.txt)
Either I'm missing something thanks to not having an arch/specific dependency list, or it's failing for some other reason beyond myself.
I'm running an Optimus NVidia+Intel laptop if it helps at all, but I don't think that this would affect compiling.

**Comment by Azkoh** [comment]
Try this AUR
https://aur.archlinux.org/packages/alvr-git/
It can provide everything you need to build

**Comment by xytovl** [comment]
Which version are you trying to compile?
This specific build failure should have been fixed since https://github.com/alvr-org/ALVR/commit/a9847202fa0035018442a20f0da6cb867f758b90

**Comment by yackaro** [comment]
I have tried both the alvr-git ppackage on the AUR, as well as the latest release's source. I have not tried pulling the latest directly from the repo yet.

**Comment by Azkoh** [comment]
> I have tried both the alvr-git ppackage on the AUR, as well as the latest release's source. I have not tried pulling the latest directly from the repo yet.

I would try cloning the current repo, if you used makepkg -s to build the package you should already have deficiencies to build directly from repo.

**Comment by yackaro** [comment]
Pulling the latest still fails, with a different error.
[Here's the output of that.](https://github.com/alvr-org/ALVR/files/6756496/Output_buildfail2.txt)

**Comment by xytovl** [comment]
Your ffmpeg does not have vulkan support, which can be fixed either by compiling ffmpeg with required flags (vulkan, vaapi, drm), or using the bundled ffmpeg (--bundle-ffmpeg flag)

**Comment by yackaro** [comment]
I finally got an error I could follow after throwing in the bundled ffmpeg, and installed nasm as a dependency. Seems to me like the alvr-git AUR package does not have dependencies set up properly, as well as the build instructions need to be updated with arch/manjaro dependency list.

**Comment by yackaro** [comment]
Further investigation on a fresh system install, the dependencies missing on the AUR repo seem to be nasm and clang.
After adding nasm and clang manually, the AUR repo successfully compiled as it should. Not sure whether I should steer this thread to cover the missing dependency tree, or close it and make a new thread for it.

**Comment by ckiee** [comment]
This is an issue you need to take up with the AUR package maintainer, not us.
