### ISSUE TITLE
Can't do anything once inside SteamVR on Quest 2

### ISSUE THREAD

**Issue by Okami503** [alvr-org/ALVR#988]
## Description
I can't start up any games nor can I open and use the desktop browser function of SteamVR on the Oculus Quest 2.
I followed the instructions, I have my VR dashboard set to Max Performance, everything is updated and installed, but I can't do a single thing on my computer. My headset starts up, connects, I can see the SteamVR home just fine and move around, but I just can't do anything else in the application. I can start them up on my computer, but that's it.

### Hardware
**CPU**: "AMD Ryzen 9 4900HS with Radeon Graphics, 3000 Mhz, 8 Core(s), 16 Logical Processor(s)"

**GPU**: "NVIDIA GeForce RTX 2060 with Max-Q Design"

### Installation
**ALVR Version**: 17.0.2

**SteamVR Version**: 1.21.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version**: Windows 10, 19044.1526

**Comment by Ev1lbl0w** [comment]
You are using an outdated version, can you try the latest [v18 release](https://github.com/alvr-org/ALVR/releases/tag/v18.1.0)?

I recall seeing some problems with button mappings before, I'm not sure if the triggers were affected as well but those were fixed recently.

**Comment by Okami503** [comment]
I updated to the newest release (18.10v) and it's still happening.

**Comment by Ev1lbl0w** [comment]
Can you record a clip of what happens in the headset, please?

**Comment by Okami503** [comment]
Yeah I'll do that tomorrow when I'm off work.
